spring:
  kafka:
    bootstrap-servers: "kafka1:9092,kafka2:9092,kafka3:9092"
    consumer:
      group-id: foo
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.LongDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: 'com.birse.kafka.project'
app:
  topic:
    projects: projects

logging:
  level:
    root: WARN
    org.springframework.web: INFO
    com.birse.kafka: DEBUG